### ISSUE TITLE
Sweet!

### ISSUE THREAD

**Issue by Luxonis-Brandon** [antabangun/coex#1]
Hi @antabangun ,

This is less of an issue and more of a "Wow, this work looks awesome!".

So we're going to try to get this running on DepthAI.  As it would be super cool to have something of this capability running natively on a little embedded camera.  And as a TLDR we make an ecosystem of open source hardware, software, and firmware with the end goal being to make it as easy as possible to embed performant spatial AI and CV into little things.  https://github.com/luxonis

We're just initially looking at it now, so we don't know the complexity of porting this.  But we'll be giving it a shot.

Thanks,
Brandon

**Comment by antabangun** [comment]
Hi @Luxonis-Brandon, thank you for your interest in our work! We'd be happy to help if there is any issue with porting it :)

**Comment by Luxonis-Brandon** [comment]
Thanks!  So Katsuya Hyodo took a first stab at converting it and hit a roadblock with ONNX and torch.argsort.  So he’s working on a workaround now.  

I’ll open an issue on it if for anything just Google-ability of the issue and hopefully a solution.
