### ISSUE TITLE
SceneFlow checkpoints 

### ISSUE THREAD

**Issue by jhw-go** [antabangun/coex#14]
We would like to get the pretrained model on sceneflow for our fine work, could you please offer it on google? Thanks very much!

**Comment by antabangun** [comment]
Hi,

Thank you for your interest in our work and for reaching out with your request.

I have uploaded the pretrained model on SceneFlow to Dropbox. You can download it directly from this link: [sceneflow weights](https://www.dropbox.com/s/c1v2r74tlbrrmsr/sceneflow.ckpt?dl=0)

I've also updated the README file in the repository, where you can find more details about the training process and the achieved results with this newly trained weights.

**Comment by jhw-go** [comment]
Thank you very much for your reply and your efforts, I have a new problem, I want to know the logs/stereo/CoEx/version_0 / checkpoints/ folder weight is fined on the kitti?

**Comment by antabangun** [comment]
It has been some time, but if memory serves me right, the weights in the logs/stereo/CoEx/version_0/checkpoints/ folder were indeed fine-tuned on the KITTI dataset and this was the model we reported for evaluations in our paper. 

For the updated model that's currently on the KITTI public benchmark (with improved evaluation results compared to the paper results), additional training augmentations were added, including stretching and color augmentations.

**Comment by jhw-go** [comment]
Thank you for your patient replay, I think that you research is so meaningful !!!
