### ISSUE TITLE
Question about Application - visual odometry and point cloud mapping

### ISSUE THREAD

**Issue by lsl-air** [antabangun/coex#15]
Outstanding work, may I ask how the combination of depth and VO system demonstrated on your project website was done, can you describe the process?

**Comment by antabangun** [comment]
Hi, thanks for your interest in our work.
Using the disparity map estimated by CoEx, we computed the depths and used an existing RGB-D VO method (unfortunately, I don't remember which one). Then, we accumulate the unprojected point clouds into voxels just to demonstrate the results of the depth estimates.

**Comment by lsl-air** [comment]
Thank you for your advice~
