### ISSUE TITLE
Can't reproduce the result:epe 0.69

### ISSUE THREAD

**Issue by GrimaceLittleBoss** [antabangun/coex#17]
Hi! Thank you for the great works!
I'm trying to Re-train the model, But I got epe 0.799957.
I wonder if I ignore some setting.
I only made a few changes in cfg_coex.yaml:

device: [0,1,2,3,4,5,6,7]
  train_on: 
    sceneflow: True
    kitti12: False
    kitti15: False
    kittiraw: False
    kitti360: False

Experiments were on 8 3090Ti GPUs
I want to know on which dataset did you train and get epe 0.69?

**Comment by antabangun** [comment]
Hi, thanks for your interest in our work!
That result was trained on only SceneFlow data.

I never tried training the model with multiple GPUs, I wonder if that had any effect on the results.
I think training this model is relatively quick. So if you don't mind could you try training for more epochs to see what happens. Maybe with
```
sceneflow_max_epochs: 20
sceneflow_milestones: [15]
```
Or even 
```
sceneflow_max_epochs: 30
sceneflow_milestones: [25]
```
if possible. 
Thanks!
