### ISSUE TITLE
torch.argsort

### ISSUE THREAD

**Issue by Luxonis-Brandon** [antabangun/coex#2]
Thanks again for this work.  This issue is more-so to document our initial conversation attempts to get this to run with DepthAI.  The first step is to convert to ONNX, and then from there OpenVINO is used to make it run on the Myriad X.

Katsuya Hyodo (PINTO0309) is working on the conversion to ONNX now, and ran into torch.argsort not being supported in ONNX, so he’s making an attempt at working around it now.  

Full ONNX conversion error message below:
```
Traceback (most recent call last):
  File "demo.py", line 49, in <module>
    torch.onnx.export(pose_ssstereo, (x, x), f"coex_{H}x{W}.onnx", opset_version=13)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 990, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 944, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_registry.py", line 116, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator argsort to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

**Comment by antabangun** [comment]
Sorry, but we haven't tried converting to ONNX before. Instead, we've converted the model to TorchScript, but it runs a little bit slower compared to the original model (37 Hz --> 34 Hz). We've updated the repo to include the TorchScript model (in ./zoo/torchscript) and a demo code for it. I hope it can help you.

**Comment by PINTO0309** [comment]
I am thinking that I can probably export to ONNX by replacing argsort with sort, but I will need to retrain the model from scratch.
https://pytorch.org/docs/stable/onnx.html
![Screenshot 2021-08-14 23:23:48](https://user-images.githubusercontent.com/33194443/129449475-5d35b20a-9917-4bbc-8c4a-dabc35b7e300.png)
- PSMNet.py
```python
            # pool_ind_ = cost.argsort(2, True)[:, :, :k]
            _, ind = cost.sort(2, True)
            pool_ind_ = ind[:, :, :k]
```
- regression.py
```python
            # pool_ind_ = cost.argsort(2, True)[:, :, :k]
            _, ind = cost.sort(2, True)
            pool_ind_ = ind[:, :, :k]
```

**Comment by antabangun** [comment]
I just tried your suggestion to replace argsort with sort, and it works nicely when I ran the demo code without having to re-train the model :))

**Comment by PINTO0309** [comment]
ONNX export was successful. Thank you for your cooperation.
![Screenshot 2021-08-15 00:02:41](https://user-images.githubusercontent.com/33194443/129450573-1c04856c-32d8-42ff-8406-7ca1cae9ddc9.png)

**Comment by PINTO0309** [comment]
Optimized ONNX.
![Screenshot 2021-08-15 00:17:08](https://user-images.githubusercontent.com/33194443/129450972-6e706b08-e21e-4f94-87d8-e94784d56717.png)
![Screenshot 2021-08-15 00:18:01](https://user-images.githubusercontent.com/33194443/129451009-c9d3ca6f-cac2-4081-9515-7b1571e605fa.png)

**Comment by antabangun** [comment]
Glad to hear it works!

**Comment by PINTO0309** [comment]
For the time being, I have only quoted and committed the models that I converted to ONNX and OpenVINO. Thanks!

‐ GPLv3 LICENSE
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/135_CoEx

**Comment by PINTO0309** [comment]
I've issued a pull request to PyTorch. It may be rejected.
https://github.com/pytorch/pytorch/pull/63283

**Comment by Luxonis-Brandon** [comment]
Sweet, thanks both!  This is exciting.  And discussing offline with @PINTO0309 it seems the conversion to run on DepthAI via OpenVINO seems to fail with some unsupported layers:
```
MODEL=coex
H=240
W=320
${INTEL_OPENVINO_DIR}/deployment_tools/inference_engine/lib/intel64/myriad_compile \
> -m openvino/${H}x${W}/FP16/${MODEL}_${H}x${W}.xml \
> -ip U8 \
> -VPU_NUMBER_OF_SHAVES 4 \
> -VPU_NUMBER_OF_CMX_SLICES 4 \
> -o openvino/${H}x${W}/myriad/${MODEL}_${H}x${W}.blob
Inference Engine: 
    IE version ......... 2021.4.0
    Build ........... 2021.4.0-3839-cd81789d294-releases/2021/4
[Warning][VPU][Config] Deprecated option was used : VPU_MYRIAD_PLATFORM
[ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/inference-engine/src/vpu/graph_transformer/src/frontend/frontend.cpp:439 Failed to compile layer "BatchNormalization_602/variance/Fused_Add_": [ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/inference-engine/src/vpu/graph_transformer/src/model/model.cpp:198 duplicateData error: while duplicating BatchNormalization_602/variance/Fused_Add_@weights Const data got different desc and content byte sizes (49152 and 196608 respectively)
```

So we'll investigate these, seeing if we can find equivalent layers to replace these unsupported ones.

**Comment by antabangun** [comment]
I forgot to mention that currently the network expects the dimension sizes to be divisible by 32, so H=240 would likely throw an error. I'll modify the model to use bilinear interpolation so that it can accept any input size and give you an update.

**Comment by PINTO0309** [comment]
@antabangun Thanks for the advice. 

Currently, there is no problem in the structure of the model because it is automatically scaled to multiples of 32 by **`Resize (bilinear interpolation)`** at the time of conversion to ONNX.
- CoEx - 240x320
![Screenshot 2021-08-15 13:43:58](https://user-images.githubusercontent.com/33194443/129467427-9336c6b6-d45c-4862-acb4-4e27e3f66612.png)

Just to be sure, I regenerated ONNX with **`320x320`** resolution as you advised, and converted it using the **`ONNX -> OpenVINO -> Myriad Blob`** flow, and got the same error. Therefore, this error suggests that there is no problem with your model, but with OpenVINO or Myriad Blob Compiler.
```
MODEL=coex
H=320
W=320
$ ${INTEL_OPENVINO_DIR}/deployment_tools/inference_engine/lib/intel64/myriad_compile \
> -m openvino/${H}x${W}/FP16/${MODEL}_${H}x${W}.xml \
> -ip U8 \
> -VPU_NUMBER_OF_SHAVES 4 \
> -VPU_NUMBER_OF_CMX_SLICES 4 \
> -o openvino/${H}x${W}/myriad/${MODEL}_${H}x${W}.blob
Inference Engine: 
	IE version ......... 2021.4.0
	Build ........... 2021.4.0-3839-cd81789d294-releases/2021/4
[Warning][VPU][Config] Deprecated option was used : VPU_MYRIAD_PLATFORM
[ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/inference-engine/src/vpu/graph_transformer/src/frontend/frontend.cpp:439 Failed to compile layer "BatchNormalization_602/variance/Fused_Add_": [ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/inference-engine/src/vpu/graph_transformer/src/model/model.cpp:198 duplicateData error: while duplicating BatchNormalization_602/variance/Fused_Add_@weights Const data got different desc and content byte sizes (49152 and 196608 respectively)
```
@antabangun I am very happy to have a meaningful discussion. Thank you. :smile: 

To. @Luxonis-Brandon 
I think it's rude to keep discussing non-essential issues of the model in this issue, so I think it's appropriate to move the discussion to another workspace.

**Comment by Luxonis-Brandon** [comment]
Thanks and sorry @PINTO0309 .  Will close this and move the conversion to Myriad X blob elsewhere.
