### ISSUE TITLE
cuda out of memory in training 

### ISSUE THREAD

**Issue by 1019679637** [antabangun/coex#5]
Hello, first I will say this is a great work@antabangun
This issue is about training. For example, When cfg['training']['sceneflow_max_epochs'] = 10, the training starts from epoch=0 to epoch=10. When last epoch starts(just epoch=10), the cuda memory increase largely(just from 10.5GB to 16.5GB), and the training time becomes quickly!(from 18min/epoch to 7min/epoch)
![image](https://user-images.githubusercontent.com/59300168/137591888-0e809c6d-8764-4090-86f1-94876a249d7e.png)

![image](https://user-images.githubusercontent.com/59300168/137591866-fbfb6771-7ec9-46dc-a1fc-2a2360fe1426.png)
![image](https://user-images.githubusercontent.com/59300168/137591939-065139bf-8b8c-41fe-b3fa-484593a0da67.png)

So, when I trained on GPU(memory=11GB), I will appear this mistake:
![image](https://user-images.githubusercontent.com/59300168/137592109-09b1690e-fddc-4803-aa7d-3fa108dfd501.png)

**Comment by antabangun** [comment]
Hi, thank you for your interest in this work. Yes this issue happens when we set "stochastic_weight_avg=True" (SWA) in the pytorch lightning trainer flag. If you remove the stochastic_weight_avg flag, then the training stops at epoch 9 (as intended with max epoch = 10) and immediately goes to the testing phase. But I usually find better result with SWA activated.

So actually, the lightning documentation mention that this way of using SWA is deprecated, and SWA should be passed into the trainer callback instead. Maybe this will solve this issue, and I'm planning to modify the code to the newer method when I find the time. 
I hope this helps!

**Comment by 1019679637** [comment]
OK, I think this is a great answer to me! Besides, I found that if I add some new designed modules，the memory usage will increase. So I need to use two or more GPUs. When I use more GPUs to test the original work(coex) , the EPE result will increase compared with only use one GPU. So can you explain the reason about this?
Here is the result when use two GPUs (just coex code with no other module):
![image](https://user-images.githubusercontent.com/59300168/137609470-25e668d6-e15e-491e-9fea-ffe0afc5c8b8.png)
 Here is the result when use one GPU (just coex code with no other module):
![image](https://user-images.githubusercontent.com/59300168/137609486-2a5a0d69-9535-43b6-befa-2710ba48b4f6.png)

I  am looking forward to your wonderful reply!
Thank you.

**Comment by antabangun** [comment]
Wow, I didn't try experimenting with more than one GPU before, so this is also the first time I see this kind of result. This is strange, but I'll try it myself too and try to find out the reason. 
I'd also appreciate it if you let me know if you figure out the problem :)

**Comment by 1019679637** [comment]
OK ,thank you very much, I will have a try !

**Comment by Iverson-zq** [comment]
> OK, I think this is a great answer to me! Besides, I found that if I add some new designed modules，the memory usage will increase. So I need to use two or more GPUs. When I use more GPUs to test the original work(coex) , the EPE result will increase compared with only use one GPU. So can you explain the reason about this? Here is the result when use two GPUs (just coex code with no other module): ![image](https://user-images.githubusercontent.com/59300168/137609470-25e668d6-e15e-491e-9fea-ffe0afc5c8b8.png) Here is the result when use one GPU (just coex code with no other module): ![image](https://user-images.githubusercontent.com/59300168/137609486-2a5a0d69-9535-43b6-befa-2710ba48b4f6.png)
> 
> I am looking forward to your wonderful reply! Thank you.

Hi，excuse me. I wonder if you retrained the model checkpoints you used when testing the Scene Flow dataset. I would appreciate it if you could reply to me
