### ISSUE TITLE
About the speed

### ISSUE THREAD

**Issue by jucic** [antabangun/coex#7]
Hello, thanks for your nice job.
I tried to run coex on my own RTX2080 Ti, however, for kitti data(reso of 376*1241), it takes about 45ms per image(about 22 fps), and I believe there is nobody else using this GPU when I am running the code, do you know why？
one more question, I found that there are usually some artifacts in textureless region such as the red box region of the follow image
<img width="1233" alt="4C54CE19-CFDA-4403-A9B3-64C8E394F22D" src="https://user-images.githubusercontent.com/17615552/138818417-9a1fcfcc-8597-475a-bf00-7c1d046ad6bf.png">
.

**Comment by ZhangYuanQing99** [comment]
Hi, thanks for your discussion.
I tried to run coex on my PC(Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   2.90 GHz) without GPU, it takes about 70s to process per image.  Is this normal? I'm looking forward to your reply.
