### ISSUE TITLE
TensorRT model

### ISSUE THREAD

**Issue by kaleab-k** [antabangun/coex#8]
Hello @antabangun,  
Thank you for the great work!
Have you tried converting the torchscript model to tensorrt? 
If so, can you please share either the model or how you did it? 
I tried it with torch2trt but it fails since some of the layers are not supported. 
Thank you!

**Comment by antabangun** [comment]
Hi @kaleab-k ,
Thanks for your interest!
I have not yet tried converting the model to TensorRT.
I was thinking of using the newly added official [Torch-TensorRT](https://pytorch.org/TensorRT/index.html), but haven't had the time to do so.
I can maybe try to do it and give you an update, hopefully by this week :)

**Comment by kaleab-k** [comment]
Great, thanks a lot!!

**Comment by antabangun** [comment]
I will be closing this issue now
